program cplan_;

uses
  Forms,
  Start in '..\CPLAN\START.PAS' {StartForm},
  Control in '..\CPLAN\CONTROL.PAS' {ControlForm},
  Em_newu1 in '..\CPLAN\EM_NEWU1.PAS' {TestForm},
  Winmask in '..\LISTTYPE\WINMASK.PAS',
  Featgrid in '..\CPLAN\FEATGRID.PAS' {FeatGridForm},
  Defrqry in '..\NEWWORK\DEFRQRY.PAS' {Deferral_Query},
  Defrfl in '..\NEWWORK\DEFRFL.PAS' {DefSitesFail},
  Exclqry in '..\NEWWORK\EXCLQRY.PAS' {Feature_Query},
  Excludfl in '..\NEWWORK\EXCLUDFL.PAS' {FailExSites},
  Sitelist in '..\LISTTYPE\SITELIST.PAS',
  Linklist in '..\CYBERSFE\LLIST\LINKLIST.PAS',
  Opt1 in '..\CYBERSFE\ARRAY\OPT1.PAS',
  Global in '..\CPLAN\GLOBAL.PAS',
  Contribu in '..\CPLAN\CONTRIBU.PAS' {ContributionForm},
  Toolmisc in '..\CPLAN\TOOLMISC.PAS',
  Sf_irrep in '..\CPLAN\SF_IRREP.PAS' {IrrepForm},
  Rununit in '..\CPLAN\RUNUNIT.PAS' {RunForm},
  Choosedb in '..\CPLAN\CHOOSEDB.PAS' {ChooseDBForm},
  F1find in '..\CPLAN\F1FIND.PAS' {FeaturesToTargetForm},
  S1find in '..\CPLAN\S1FIND.PAS' {AvailableSitesForm},
  S2show in '..\CPLAN\S2SHOW.PAS' {ReservedSitesForm},
  Partl_ed in '..\CPLAN\PARTL_ED.PAS' {PartEdForm},
  Options in '..\CPLAN\OPTIONS.PAS' {OptionsForm},
  Featlist in '..\LISTTYPE\FEATLIST.PAS',
  About in '..\CPLAN\ABOUT.PAS' {AboutBox},
  Dll_u1 in '..\CPLAN\Dll_u1.pas',
  Highligh in '..\CPLAN\Highligh.pas',
  Choosere in '..\CPLAN\Choosere.pas' {ChooseResForm},
  Calcfld in '..\CPLAN\Calcfld.pas' {CalcFieldForm},
  av1 in '..\ARCVIEW\av1.pas' {AVDDEForm},
  Calcdef in '..\CPLAN\Calcdef.pas',
  In_order in '..\CPLAN\In_order.pas',
  Toolview in '..\CPLAN\Toolview.pas' {ToolForm},
  Resttarg in '..\CPLAN\Resttarg.pas' {RestTargForm},
  Datastru in '..\CYBERSFE\tools\DS\Datastru.pas',
  Choices in '..\CPLAN\Choices.pas' {ChoiceForm},
  Sql_unit in '..\CPLAN\Sql_unit.pas' {SQLForm},
  Editstr in '..\CPLAN\Editstr.pas' {EditStrForm},
  Lookup in '..\CPLAN\Lookup.pas' {LookupForm},
  Binfile in '..\CPLAN\Binfile.pas',
  Bin_io in '..\CPLAN\Bin_io.pas',
  Edit in '..\CPLAN\Edit.pas' {EditForm},
  ARR2LBOX in '..\CPLAN\Arr2lbox.pas',
  itersear in '..\CPLAN\itersear.pas',
  secure in '..\CPLAN\secure.pas',
  SORTS in '..\CPLAN\Sorts.pas',
  Pred_sf4 in '..\CPLAN\Pred_sf4.pas',
  Resize in '..\CPLAN\Resize.pas',
  Sct_grid in '..\CPLAN\Sct_grid.pas' {SelectGridForm},
  reg in '..\register\reg.pas' {RegisterForm},
  Comb_run in '..\CPLAN\Comb_run.pas' {CombRunForm},
  Randtest in '..\CPLAN\Randtest.pas',
  Dde_unit in '..\CPLAN\Dde_unit.pas',
  Lbox in '..\CPLAN\Lbox.pas',
  Reports in '..\CPLAN\Reports.pas',
  minset in '..\CPLAN\minset.pas' {MinsetForm},
  pctarg in '..\CPLAN\pctarg.pas' {PCTargForm},
  Arraydb in '..\CYBERSFE\tools\DS\ARRAY\Arraydb.pas' {ArrayDebug},
  Pred_sf3 in '..\CPLAN\Pred_sf3.pas',
  rules in '..\CPLAN\rules.pas' {RulesForm},
  validate in '..\CPLAN\validate.pas',
  editrule in '..\CPLAN\editrule.pas' {EditRuleForm},
  workdir in '..\CPLAN\workdir.pas' {WorkingDirForm},
  comp2coo in '..\CPLAN\comp2coo.pas',
  c2c in '..\CPLAN\c2c.pas' {C2CForm},
  Ds in '..\DPARRAY\Ds.pas',
  OrdClass in '..\CPLAN\OrdClass.pas',
  chooseoc in '..\CPLAN\chooseoc.pas' {OrdClassForm},
  Imptools in '..\IMPORT\Imptools.pas',
  minstop in '..\IMPORT\minstop.pas' {StopMinsetForm},
  mthread in '..\CPLAN\mthread.pas',
  svalue in '..\CPLAN\svalue.pas' {SiteValueForm},
  arithrle in '..\CPLAN\arithrle.pas' {ArithmeticRuleForm},
  fldadd in '..\CPLAN\fldadd.pas' {FieldAdder: TDataModule},
  StdFctns in '..\DPARRAY\Stdfctns.pas',
  jointbl in '..\CPLAN\jointbl.pas' {JoinTableForm},
  trpt in '..\CPLAN\trpt.pas',
  datamod1 in '..\CPLAN\datamod1.pas' {DataModule1: TDataModule},
  trimini in '..\CPLAN\trimini.pas' {TrimIniForm},
  browsed in '..\CPLAN\browsed.pas' {BrowseDirForm},
  edits in '..\CPLAN\edits.pas' {EnterStrForm},
  subform in '..\CPLAN\subform.pas' {SelectSubsetForm},
  spatinfc in '..\CPLAN\spatinfc.pas' {SpatailModuleSpecForm},
  spatlink in '..\CPLAN\spatlink.pas' {SpatLinkForm},
  spatopt in '..\CPLAN\spatopt.pas' {SpatialOptionsForm},
  use_dll in '..\CPLAN\use_dll.pas' {UseDLLForm},
  spatio in '..\CPLAN\spatio.pas' {SpatIOModule: TDataModule},
  saverpt in '..\CPLAN\saverpt.pas' {SaveRptForm},
  auto_fit in '..\CPLAN\auto_fit.pas',
  batchEMS in '..\CPLAN\batchEMS.pas' {BatchEMSForm},
  reallist in '..\CPLAN\reallist.pas',
  msetinf in '..\CPLAN\msetinf.pas' {MinsetUserForm},
  destruct in '..\CPLAN\destruct.pas',
  msetexpt in '..\CPLAN\msetexpt.pas' {MinsetExpertForm},
  sub_feat in '..\CPLAN\sub_feat.pas' {StopSubsetForm},
  emr_rule in '..\CPLAN\emr_rule.pas',
  randinfo in '..\CPLAN\randinfo.pas' {RandomSelectForm},
  reinit in '..\CPLAN\reinit.pas',
  choosedbf in '..\CPLAN\choosedbf.pas' {ChooseFieldsForm},
  dbf_header in 'dbf_header.pas',
  stage_gis in '..\CPLAN\stage_gis.pas' {AddStageToGISForm},
  RedundancyCheck in '..\CPLAN\RedundancyCheck.pas',
  filter in '..\CPLAN\filter.pas' {FilterForm},
  sortoptions in '..\CPLAN\sortoptions.pas' {SortForm},
  select_tgt_field in '..\CPLAN\select_tgt_field.pas' {SelectTargetFieldForm},
  hotspots_nocomplementarity_areaindices in '..\CPLAN\hotspots_nocomplementarity_areaindices.pas',
  CombsizeRecord in '..\CPLAN\CombsizeRecord.pas',
  FirstSiteReport in '..\CPLAN\FirstSiteReport.pas',
  override_combsize in '..\CPLAN\override_combsize.pas' {OverrideCombsizeForm},
  UpdateAverageSite in '..\CPLAN\UpdateAverageSite.pas',
  getuservalidatefile in '..\CPLAN\getuservalidatefile.pas' {FormGetUserValidateFile},
  spat_progress in '..\CPLAN\spat_progress.pas' {SpatialProgressForm},
  FmxUtils in '..\dbase_editor\Fmxutils.pas',
  fast_minset in '..\CPLAN\fast_minset.pas' {FastMinsetForm},
  summarise_sites in '..\CPLAN\summarise_sites.pas' {SummariseSitesForm},
  spatDLLmanager in '..\CPLAN\spatDLLmanager.pas' {SpatDLLManagerForm},
  displaygrid in '..\CPLAN\displaygrid.pas' {DisplayGridForm},
  version in '..\CPLAN\version.pas',
  sitefeatlookup in '..\CPLAN\sitefeatlookup.pas' {SiteFeatLookupForm},
  featlookupfields in '..\CPLAN\featlookupfields.pas' {SelectFieldsForm},
  linegraph in '..\CPLAN\linegraph.pas' {LineGraphForm},
  rptMeasure2 in '..\CPLAN\rptMeasure2.pas' {ReportMeasure2Form},
  displaysites in '..\CPLAN\displaysites.pas' {DisplaySitesForm},
  displayfeatures in '..\CPLAN\displayfeatures.pas' {DisplayFeaturesForm},
  sitelookupfields in '..\CPLAN\sitelookupfields.pas' {SelectSiteFieldsForm},
  choosesiterows in '..\CPLAN\choosesiterows.pas' {ChooseSiteRowsForm},
  selectsitesortfield in '..\CPLAN\selectsitesortfield.pas' {SelectSiteSortFieldForm},
  ChooseFeatureRows in '..\CPLAN\ChooseFeatureRows.pas' {ChooseFeatureRowsForm},
  SelectFeatureSortField in '..\CPLAN\SelectFeatureSortField.pas' {SelectFeatureSortFieldForm},
  marxan in '..\CPLAN\marxan.pas' {MarxanPrototypeForm},
  marxanoptions in '..\CPLAN\marxanoptions.pas' {MarxanOptionsForm},
  displaywarnings in '..\CPLAN\displaywarnings.pas' {DisplayWarningsForm},
  marxan_summary in '..\CPLAN\marxan_summary.pas' {MarxanSummaryForm},
  BLF_process in '..\CPLAN\BLF_process.pas' {BLFProcessForm},
  random_selection in '..\CPLAN\random_selection.pas' {RandomSelectionForm},
  EasyEditTargets in '..\CPLAN\EasyEditTargets.pas' {EasyEditTargetsForm},
  import_target_field in '..\CPLAN\import_target_field.pas' {ImportTargetFieldForm},
  SummariseClumps in '..\CPLAN\SummariseClumps.pas' {SummariseClumpsForm};

{$R *.RES}

begin
  Application.Title := 'C-Plan 32 Bit';
  Application.CreateForm(TStartForm, StartForm);
  Application.Run;
end.
