program cplan;

uses
  Forms,
  Start in 'START.PAS' {StartForm},
  Control in 'CONTROL.PAS' {ControlForm},
  Em_newu1 in 'EM_NEWU1.PAS' {TestForm},
  Winmask in '..\LISTTYPE\WINMASK.PAS',
  Featgrid in 'FEATGRID.PAS' {FeatGridForm},
  Defrqry in '..\NEWWORK\DEFRQRY.PAS' {Deferral_Query},
  Defrfl in '..\NEWWORK\DEFRFL.PAS' {DefSitesFail},
  Exclqry in '..\NEWWORK\EXCLQRY.PAS' {Feature_Query},
  Excludfl in '..\NEWWORK\EXCLUDFL.PAS' {FailExSites},
  Sitelist in '..\LISTTYPE\SITELIST.PAS',
  Linklist in '..\CYBERSFE\LLIST\LINKLIST.PAS',
  Opt1 in '..\CYBERSFE\ARRAY\OPT1.PAS',
  Global in 'GLOBAL.PAS',
  Contribu in 'CONTRIBU.PAS' {ContributionForm},
  Toolmisc in 'TOOLMISC.PAS',
  Sf_irrep in 'SF_IRREP.PAS' {IrrepForm},
  Rununit in 'RUNUNIT.PAS' {RunForm},
  Choosedb in 'CHOOSEDB.PAS' {ChooseDBForm},
  F1find in 'F1FIND.PAS' {FeaturesToTargetForm},
  S1find in 'S1FIND.PAS' {AvailableSitesForm},
  S2show in 'S2SHOW.PAS' {ReservedSitesForm},
  Partl_ed in 'PARTL_ED.PAS' {PartEdForm},
  Options in 'OPTIONS.PAS' {OptionsForm},
  Featlist in '..\LISTTYPE\FEATLIST.PAS',
  About in 'ABOUT.PAS' {AboutBox},
  Dll_u1 in 'Dll_u1.pas',
  Highligh in 'Highligh.pas',
  Choosere in 'Choosere.pas' {ChooseResForm},
  Calcfld in 'Calcfld.pas' {CalcFieldForm},
  av1 in '..\ARCVIEW\av1.pas' {AVDDEForm},
  Calcdef in 'Calcdef.pas',
  In_order in 'In_order.pas',
  Toolview in 'Toolview.pas' {ToolForm},
  Resttarg in 'Resttarg.pas' {RestTargForm},
  Datastru in '..\CYBERSFE\tools\DS\Datastru.pas',
  Choices in 'Choices.pas' {ChoiceForm},
  Sql_unit in 'Sql_unit.pas' {SQLForm},
  Editstr in 'Editstr.pas' {EditStrForm},
  Lookup in 'Lookup.pas' {LookupForm},
  Binfile in 'Binfile.pas',
  Bin_io in 'Bin_io.pas',
  Edit in 'Edit.pas' {EditForm},
  ARR2LBOX in 'Arr2lbox.pas',
  itersear in 'itersear.pas',
  secure in 'secure.pas',
  SORTS in 'Sorts.pas',
  Pred_sf4 in 'Pred_sf4.pas',
  Resize in 'Resize.pas',
  Sct_grid in 'Sct_grid.pas' {SelectGridForm},
  reg in '..\register\reg.pas' {RegisterForm},
  Comb_run in 'Comb_run.pas' {CombRunForm},
  Randtest in 'Randtest.pas',
  Dde_unit in 'Dde_unit.pas',
  Lbox in 'Lbox.pas',
  Reports in 'Reports.pas',
  minset in 'minset.pas' {MinsetForm},
  pctarg in 'pctarg.pas' {PCTargForm},
  Arraydb in '..\CYBERSFE\tools\DS\ARRAY\Arraydb.pas' {ArrayDebug},
  Pred_sf3 in 'Pred_sf3.pas',
  rules in 'rules.pas' {RulesForm},
  validate in 'validate.pas',
  editrule in 'editrule.pas' {EditRuleForm},
  workdir in 'workdir.pas' {WorkingDirForm},
  comp2coo in 'comp2coo.pas',
  c2c in 'c2c.pas' {C2CForm},
  Ds in '..\DPARRAY\Ds.pas',
  OrdClass in 'OrdClass.pas',
  chooseoc in 'chooseoc.pas' {OrdClassForm},
  Imptools in '..\IMPORT\Imptools.pas',
  minstop in '..\IMPORT\minstop.pas' {StopMinsetForm},
  mthread in 'mthread.pas',
  svalue in 'svalue.pas' {SiteValueForm},
  arithrle in 'arithrle.pas' {ArithmeticRuleForm},
  fldadd in 'fldadd.pas' {FieldAdder: TDataModule},
  StdFctns in '..\DPARRAY\Stdfctns.pas',
  jointbl in 'jointbl.pas' {JoinTableForm},
  trpt in 'trpt.pas',
  datamod1 in 'datamod1.pas' {DataModule1: TDataModule},
  trimini in 'trimini.pas' {TrimIniForm},
  browsed in 'browsed.pas' {BrowseDirForm},
  edits in 'edits.pas' {EnterStrForm},
  subform in 'subform.pas' {SelectSubsetForm},
  spatinfc in 'spatinfc.pas' {SpatailModuleSpecForm},
  spatlink in 'spatlink.pas' {SpatLinkForm},
  spatopt in 'spatopt.pas' {SpatialOptionsForm},
  use_dll in 'use_dll.pas' {UseDLLForm},
  spatio in 'spatio.pas' {SpatIOModule: TDataModule},
  saverpt in 'saverpt.pas' {SaveRptForm},
  auto_fit in 'auto_fit.pas',
  batchEMS in 'batchEMS.pas' {BatchEMSForm},
  reallist in 'reallist.pas',
  msetinf in 'msetinf.pas' {MinsetUserForm},
  destruct in 'destruct.pas',
  msetexpt in 'msetexpt.pas' {MinsetExpertForm},
  sub_feat in 'sub_feat.pas' {StopSubsetForm},
  emr_rule in 'emr_rule.pas',
  randinfo in 'randinfo.pas' {RandomSelectForm},
  reinit in 'reinit.pas',
  choosedbf in 'choosedbf.pas' {ChooseFieldsForm},
  dbf_header in '..\CSVEDIT\dbf_header.pas',
  stage_gis in 'stage_gis.pas' {AddStageToGISForm},
  RedundancyCheck in 'RedundancyCheck.pas',
  filter in 'filter.pas' {FilterForm},
  sortoptions in 'sortoptions.pas' {SortForm},
  select_tgt_field in 'select_tgt_field.pas' {SelectTargetFieldForm},
  hotspots_nocomplementarity_areaindices in 'hotspots_nocomplementarity_areaindices.pas',
  CombsizeRecord in 'CombsizeRecord.pas',
  FirstSiteReport in 'FirstSiteReport.pas',
  override_combsize in 'override_combsize.pas' {OverrideCombsizeForm},
  UpdateAverageSite in 'UpdateAverageSite.pas',
  getuservalidatefile in 'getuservalidatefile.pas' {FormGetUserValidateFile},
  spat_progress in 'spat_progress.pas' {SpatialProgressForm},
  FmxUtils in '..\dbase_editor\Fmxutils.pas',
  fast_minset in 'fast_minset.pas' {FastMinsetForm},
  summarise_sites in 'summarise_sites.pas' {SummariseSitesForm},
  spatDLLmanager in 'spatDLLmanager.pas' {SpatDLLManagerForm},
  displaygrid in 'displaygrid.pas' {DisplayGridForm},
  version in 'version.pas',
  sitefeatlookup in 'sitefeatlookup.pas' {SiteFeatLookupForm},
  featlookupfields in 'featlookupfields.pas' {SelectFieldsForm},
  linegraph in 'linegraph.pas' {LineGraphForm},
  rptMeasure2 in 'rptMeasure2.pas' {ReportMeasure2Form},
  displaysites in 'displaysites.pas' {DisplaySitesForm},
  displayfeatures in 'displayfeatures.pas' {DisplayFeaturesForm},
  sitelookupfields in 'sitelookupfields.pas' {SelectSiteFieldsForm},
  choosesiterows in 'choosesiterows.pas' {ChooseSiteRowsForm},
  selectsitesortfield in 'selectsitesortfield.pas' {SelectSiteSortFieldForm},
  ChooseFeatureRows in 'ChooseFeatureRows.pas' {ChooseFeatureRowsForm},
  SelectFeatureSortField in 'SelectFeatureSortField.pas' {SelectFeatureSortFieldForm},
  marxan in 'marxan.pas' {MarxanPrototypeForm},
  marxanoptions in 'marxanoptions.pas' {MarxanOptionsForm},
  displaywarnings in 'displaywarnings.pas' {DisplayWarningsForm},
  marxan_summary in 'marxan_summary.pas' {MarxanSummaryForm},
  BLF_process in 'BLF_process.pas' {BLFProcessForm},
  random_selection in 'random_selection.pas' {RandomSelectionForm},
  EasyEditTargets in 'EasyEditTargets.pas' {EasyEditTargetsForm},
  import_target_field in 'import_target_field.pas' {ImportTargetFieldForm},
  SummariseClumps in 'SummariseClumps.pas' {SummariseClumpsForm},
  MarZone_interface in 'MarZone_interface.pas' {xxrrt},
  ZCDDE_unit in 'ZCDDE_unit.pas' {ZCDDEForm},
  open_ZC_GIS in 'open_ZC_GIS.pas' {Open_ZC_GIS_Form};

{$R *.RES}

begin
  Application.Title := 'C-Plan 32 Bit';
  Application.CreateForm(TStartForm, StartForm);
  Application.CreateForm(TFeatGridForm, FeatGridForm);
  Application.Run;
end.
